### PR TITLE
1.5.2

### PR DESCRIPTION
**Pull request by kellyroach-optimizely**
## 1.5.2
June 13, 2018

### New Features
* Updated SDK targets to Xcode 9.4 recommended settings, pod update'd third party Cocoapods used by the 2 demo apps, and eliminated Xcode 9.4 Build and Analyze warnings for SDK targets.

### CODE REVIEW

**Review by mikeproeng37 — APPROVED** [review]
lgtm

**Comment by kellyroach-optimizely** [comment]
TEST
* sh ./Scripts/build_all.sh PASSED
* 4 Analyze *.framework's PASSED
* 2 Analyze demo apps PASSED
* 8+1 iOS test suites PASSED
* 7+1 tvOS test suites PASSED
* 2 demo apps (8415331295) run PASSED
* 2 demo apps (8415331295) predicted results on OPTIMIZELY.COM PASSED
```
                   iOS     tvOS
    variation_a    0/11    0/6
    variation_b    6/6     4/4
```
* 2 "iTunes Connect" "Validate..." PASSED
* Carthage installation into ~/OptimizelyCarthageTest app PASSED
```
    github "optimizely/objective-c-sdk" "a12c3e7901c0cd7ae3609e5fc29c25594e33f466"
    default       0/19
    treatment     17/20
```
* ~/OptimizelyCarthageTest app "iTunes Connect" "Validate..." PASSED

**Comment by kellyroach-optimizely** [comment]
TEST: 1.5.2 SDK somehow fed a V4 datafile intended for 2.x SDK
* Experimentation indicates that specifying projectId of a V4 datafile
will provoke 1.5.2 SDK to request older style
https://cdn.optimizely.com/public/PROJECTID/datafile_v3.json
instead of a newer style, such as
https://cdn.optimizely.com/json/PROJECTID.json
The result is <Code>AccessDenied</Code> from OPTIMIZELY.COM .
* Experimentation indicates if we build app with a downloaded V4 datafile,
then runtime will report:
[OPTIMIZELY SDK][ERROR]:Provided OPTLYBuilder object is invalid

CONCLUDE: These are tolerable outcomes for attempting to use a V4 datafile
in a 1.5.2 SDK which doesn't support V4 datafiles with Optimizely Feature Management .
Users should upgrade to objective-c-sdk 2.x to gain support for V4 datafiles.

**Comment by kellyroach-optimizely** [comment]
TEST VariablesTest, ManualTest, Xcode 9.4.1

* VariablesTest PASSED
```
    default       0/43
    treatment    39/43
```
* ManualTest PASSED
```
    default       0/49
    treatment    46/46
```
* Xcode "Version 9.4.1 (9F2000)" released June 13, 2018 PASSED
No ill effect on already obtained 0 Build and 0 Analyze warnings on framework and demo app targets.

**Pull request merged**
