### PR TITLE
Carthage error submodule fmdb & json was not removed.

### PR DESCRIPTION
**Pull request by msohailhussain**
#217

### CODE REVIEW

**Comment by msohailhussain** [comment]
@kellyroach-optimizely

**Comment by kellyroach-optimizely** [comment]
build

**Comment by kellyroach-optimizely** [comment]
TEST
* "git submodule status" should be clean, no "fatal" PASSED
* "cat .gitmodules" is expected to print 
"cat: .gitmodules: No such file or directory" PASSED
* grep -i -r "submodule" . > ~/Temp/submodule.txt
The ~/Temp/submodule.txt should be clean.
* git ls-files --stage | grep 160000
Should be no output lines. (Or delete the directories this
command discovers.) PASSED
* Clean / Build OptimizelyiOSDemoApp Linker Warnings
There are 1 Amplitude and 10 Mixpanel warnings which aren't
"Linker Warnings" and aren't regression but are familiar to us.
The OptimizelyiOSDemoApp and OptimizelyTVOSDemoApp build and
run fine. PASSED
* "git submodule init"
should act like a NOP (no output) PASSED
* 8 iOS test suites PASSED
* grep test
```
    $ grep -i -r FMDB . | grep -v OPTLY | grep -v optly | grep -v optimizely | grep -v git > ~/Temp/FMDB.txt
    $ grep -i -r JSONModel . | grep -v OPTLY | grep -v optly | grep -v optimizely | grep -v git > ~/Temp/JSONModel.txt
```
should only contain harmless lines PASSED
* build_all.sh PASSED
* README.md "Carthage" installation instructions into a
CarthageTest sample app involving "carthage update" provide
a Cartfile specifying this commit were followed.  The
"Carthage" installation instructions succeeded, the
CarthageTest app built and ran fine.  PASSED

**Review by kellyroach-optimizely — APPROVED** [review]

**Comment by kellyroach-optimizely** [comment]
APPROVED

**Pull request merged**
