### PR TITLE
Kroach/oasis 1706 numeric

### PR DESCRIPTION
**Pull request by kellyroach-optimizely**
OASIS-1706 Numeric metrics support in SDK

The shortest summary possible is "Add new 'value' event key that allows 'double'
values similar to the preexisting 'revenue' event key that allows 'long long'
values and 'revenue' is retained."

### CODE REVIEW

**Review by mikeproeng37 — APPROVED** [review]
Lgtm. Make sure to Squash and Merge

**Comment by mikeproeng37** [comment]
Build

**Comment by mikeproeng37** [comment]
build

**Comment by kellyroach-optimizely** [comment]
TEST:
* sh ./Scripts/build_all.sh PASSED
* 8 iOS test suites PASSED
* OptimizelySDKiOSUniversalTests PASSED
* OptimizelySDKiOS Analyze PASSED
* OptimizelyiOSDemoApp PASSED
* 7 tvOS test suites PASSED
* OptimizelySDKTVOSUniversalTests PASSED
* OptimizelySDKTVOS Analyze PASSED
* OptimizelyTVOSDemoApp PASSED

CONCLUDE: PASSED modulo 1 occurrence of "Flakey Xcode debugger"

**Pull request merged**
