### PR TITLE
Release iOS 2.0.0-beta1

### PR DESCRIPTION
**Pull request by kellyroach-optimizely**
OASIS-2505 Release objective-c-sdk 2.0.0-beta1

New Features of objective-c-sdk 2.0.0-beta1 are described in the release message
in CHANGELOG.md including:
* The isFeatureEnabled:userId:attributes: API to determine whether to show a feature to a user.
* The getEnabledFeatures:attributes: API which returns an array of enabled feature key strings.
* Feature Variables to configure or parameterize your feature. There are four variable types: BOOL, double, int, NSString*.

This P.R. bumps version number to 2.2.0-beta1 .  We are collapsing all the version numbers
of our Optimizely frameworks down to a single version number OPTIMIZELY_SDK_VERSION
== "2.2.0-beta1" and will be using a single "git tag" going forward for each objective-c-sdk
release.  There is also a major overhaul of Optimizely's release.sh script included.

### CODE REVIEW

**Comment by kellyroach-optimizely** [comment]
build

**Comment by kellyroach-optimizely** [comment]
TEST:
* sh ./Scripts/build_all.sh PASSED
* 4 Analyze PASSED
* 8+1 iOS test suites PASSED
* 7+1 tvOS test suites PASSED
* 2 DemoApp's
[OPTIMIZELY SDK][INFO]:[EVENT DISPATCHER] Successfully tracked event sample_conversion for user 130120
OptimizelyTVOSDemoApp[46073:10649742] [OPTIMIZELY SDK][INFO]:[EVENT DISPATCHER] Successfully tracked event sample_conversion for user 139918
PASSED
* 2 workspace DemoApp's "Validate..." to iTunes Connect PASSED
* Carthage Installation instructions against OptimizelyCarthageTest app with  "Validate..." to iTunes Connect PASSED

**Review by mikeproeng37 — APPROVED** [review]
lgtm

**Comment by wangjoshuah** [comment]
build

**Pull request merged**
