### PR TITLE
Re-enable SourceClear

### PR DESCRIPTION
**Pull request by nchilada**
## Summary
Prep for 3.0 release

## Issues
- OASIS-4078

### CODE REVIEW

**Comment by ooola** [comment]
lgtm

**Review by aliabbasrizvi — APPROVED** [review]

**Comment by nchilada** [comment]
Thanks for the reviews! @mikeng13 looks like we might need to kick off the compat tests for this to be mergeable?

**Comment by thomaszurkan-optimizely** [comment]
build

**Review by thomaszurkan-optimizely — APPROVED** [review]
LGTM

**Pull request merged**
