### PR TITLE
Release 2.0.2-beta2

### PR DESCRIPTION
**Pull request by kellyroach-optimizely**
Release 2.0.2-beta2

Add environments support to SDK with SDK key initialization. A new sdkKey property has been added to OPTLYManagerBuilder that is an alternative to the older projectId property.

### CODE REVIEW

**Comment by kellyroach-optimizely** [comment]
TEST:
* sh ./Scripts/build_all.sh PASSED
* 4 Analyze *.framework's PASSED
* 2 Analyze demo apps PASSED
* 8+1 iOS test suites PASSED
* 7+1 tvOS test suites PASSED (*)
* 2 demo apps run PASSED
* 2 demo apps predicted results on OPTIMIZELY.COM PASSED
```
                iOS    tvOS
variation_a    0/11     0/8
variation_b     5/5     4/4
```
* 2 demo apps "iTunes Connect" "Validate..." PASSED
* Carthage installation into ~/OptimizelyCarthageTest app PASSED
```
default         0/42
treatment      24/28
```
* ~/OptimizelyCarthageTest app "iTunes Connect" "Validate..." PASSED

(*) Powercycled Xcode on tvOS universal test, 2nd try OK.

**Comment by kellyroach-optimizely** [comment]
TEST: Mobile Release Test Plan

CASE: VariablesTest
```
default         0/47
treatment      41/42
```

CASE: FeatureVariablesTest
```
default         0/40
treatment      24/26
```

**Comment by kellyroach-optimizely** [comment]
build

**Review by mikeproeng37 — APPROVED** [review]
lgtm

**Pull request merged**
