### PR TITLE
fix(emptybucketingid): Empty bucketing id should be acceptable.

### PR DESCRIPTION
**Pull request by msohailhussain**
## Summary
Empty bucketing ID should be acceptable for all `getVariation`, `getFeatureForRollout`, `getVariationForFeatureGroup`
## Test plan
Unit test added.

### CODE REVIEW

**Review by yasirfolio3 — APPROVED** [review]
LGTM

**Comment by msohailhussain** [comment]
build

**Review by thomaszurkan-optimizely — APPROVED** [review]
Looks good to me.

**Comment by mikeproeng37** [comment]
I am running compat suite tests on Travis here: https://travis-ci.com/optimizely/fullstack-sdk-compatibility-suite/builds/99034529

**Comment by mikeproeng37** [comment]
Ok this passed!

**Pull request merged**
