### PR TITLE
1.5.0 rc

### PR DESCRIPTION
**Pull request by alda-optimizely**

### CODE REVIEW

**Review by wangjoshuah — APPROVED** [review]
Lgtm

**Comment by kellyroach-optimizely** [comment]
TEST:
* 8 iOS test suites
* iOS universal test suite
* 7 tvOS test suites
* tvOS universal test suite
* iOS and tvOS demo apps
* iOS demo app with WiFi turned off/on at various points while exercising it.
PASSED

**Comment by kellyroach-optimizely** [comment]
There was some oral discussion about Kelly Roach's observation of "1.5.0-RC-rc" in project "Build Settings" when a "SUFFIX" is set equal to "0-RC" .  The reply is the odd "1.5.0-RC-rc" will not actually make it into the COCOAPODS.ORG "Release" which will be "1.5.0-RC" despite it all.  We accept this explanation.

**Review by kellyroach-optimizely — APPROVED** [review]
Approving.

**Pull request merged**
