### PR TITLE
Fixes an issue where bridging an Objective-C type called Optional into a Swift-based project causes LLDB issues

### PR DESCRIPTION
**Pull request by tprevost-phunware**
I've found that bridging an Objective-C protocol called `Optional` into a Swift-based project causes LLDB to sometimes not be able to distinguish between Optimizely's `Optional` and `Swift.Optional`. For example, if you set a breakpoint inside a closure, then add
```
[weak self]
```
to the closure, then hit the breakpoint during execution and try to `po` anything in the debugger, you'll get this:

> error: <EXPR>:1:11: error: 'Optional' is ambiguous for type lookup in this context
> extension Optional where Wrapped: $__lldb_context {                            
>           ^~~~~~~~
> 
> Swift.Optional:1:13: note: found this candidate
> public enum Optional<Wrapped> : ExpressibleByNilLiteral {
>             ^
> 
> OptimizelySDKCore.Optional:1:17: note: found this candidate
> public protocol Optional {
>                 ^
> 
> error: <EXPR>:18:5: error: value of type 'Optional<PlayerViewController>' has no member '$__lldb_wrapped_expr_8'
>     $__lldb_injected_self.$__lldb_wrapped_expr_8(     
>     ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~

This PR simply renames `Optional` to `OPTLYOptional`, which I have found fixes the issue.

I tried using `NS_SWIFT_NAME(OPTLYOptional)`, but that still causes LLDB to spit out errors like the above, because `NS_SWIFT_NAME(OPTLYOptional)` seems to only create a _typealias_ for Optimizely's `Optional` type and does not actually replace the name at all.

Have I run all the tests to make sure they still pass? Yes. Well, the OptimizelySDKCoreiOS and OptimizelySDKiOS tests at least. I couldn't find a way to just run _all_ the tests. I tried some of the tvOS tests, but they wouldn't even build, saying they could not find the file `<OptimizelySDKShared/OPTLYDatafileConfig.h>`. 😕

### CODE REVIEW

**Comment by TylerTheCompiler** [comment]
I've also made a Swift bug report [here](https://bugs.swift.org/browse/SR-8120).

**Comment by tprevost-phunware** [comment]
I've also made a bug report [here](https://bugs.swift.org/browse/SR-8120).

**Review by thomaszurkan-optimizely — APPROVED** [review]
LGTM

**Comment by tprevost-phunware** [comment]
Actually, this _may_ not be needed anymore since the Swift LLDB team has apparently fixed this issue here: https://github.com/apple/swift-lldb/pull/750

**Review by thomaszurkan-optimizely — CHANGES_REQUESTED** [review]
@tprevost-phunware thank you so much for your contribution.  I would have made the same change. Can you please sign this and I will merge your changes?
https://docs.google.com/a/optimizely.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform

**Comment by tprevost-phunware** [comment]
@thomaszurkan-optimizely Sure thing. Done!

**Review by thomaszurkan-optimizely — APPROVED** [review]

**Comment by asaschachar** [comment]
@tprevost-phunware Thanks for the patch to the Optimizely Objective-C SDK! Hopefully it's now a bit easier to use for the Swift projects out there. Feel free to reach out to me at asa@optimizely.com if you are at all interested in joining Optimizely full-time!

**Comment by tprevost-phunware** [comment]
No prob, @asaschachar! Glad I could help! Yeah I'll see if we can update to the latest version of the Optimizely SDK on our project (we're still on 1.5.0 unfortunately) to see this fix in action! Oh and thanks for the offer! I'm not looking for a job at the moment, but I'll keep Optimizely in mind for the future! :)

**Pull request merged**
