### PR TITLE
deprecate live variable APIs

### PR DESCRIPTION
**Pull request by AbdurRafay**

### CODE REVIEW

**Comment by kellyroach-optimizely** [comment]
OptimizelyTest.m contains
```
- (nullable NSString *)variableString:(nonnull NSString *)variableKey ...
```
which should be removed now.

**Review by kellyroach-optimizely — CHANGES_REQUESTED** [review]
OptimizelyTest.m shouldn't contain "variableString:"

**Comment by kellyroach-optimizely** [comment]
OPTLYDatafileKeys.m+.h
It doesn't seem that
```
    NSString * const OPTLYDatafileKeysVariationVariables = @"variables";
```
is being referenced anymore.  This should be removed.  Corollary to that, all remaining occurrences of "variables" in a couple *.m test files and numerous occurrences in *.json files should also be removed.

**Comment by AbdurRafay** [comment]
Occurrences of "variables" in json files under variations node are not removed as they will be used as variableUsageInstance in feature variable & rollout task.

Let me know if they should also removed in this PR.

**Comment by kellyroach-optimizely** [comment]
TEST:
* sh ./Scripts/build_all.sh PASSED
* iOS & tvOS Clean / Build / Analyze PASSED
* iOS & tvOS demo apps PASSED
* sh ./Scripts/local_travis.sh PASSED
* 2+2 iOS & tvOS IDE test suites spot check PASSED

We accept that "variables" is not removed for the reason Abdur Rafay mentioned.

**Review by kellyroach-optimizely — APPROVED** [review]

**Pull request merged**
