### PR TITLE
Fix impression sent from feature experiment variation toggled off.

### PR DESCRIPTION
**Pull request by mikeproeng37**

### CODE REVIEW

**Review by aliabbasrizvi — APPROVED** [review]
Changes look good to me.

**Comment by kellyroach-optimizely** [comment]
CODE REVIEW
* The objective-c-sdk code change may emit an additional log message that javascript-sdk wouldn't emit proceeding along one code path, but OW, the call-return behavior looks identical.
* Changes to modified testIsFeatureEnabledWithFeatureFlagEnabledAndUserIsBeingExperimented look sensible wrt the purpose of the bug fix the P.R. is trying to achieve.

**Comment by kellyroach-optimizely** [comment]
TEST:
* testIsFeatureEnabledWithFeatureFlagEnabledAndUserIsBeingExperimented
located and individually tested.  It PASSED
* sh ./Scripts/build_all.sh PASSED in (2) above
* 4 Analyze *.framework's PASSED
* 2 Analyze demo apps PASSED
* 8+1 iOS test suites PASSED (*)
* 7+1 tvOS test suites PASSED
* 2 demo apps run PASSED
* 2 demo apps predicted results on OPTIMIZELY.COM PASSED
```
                iOS     tvOS
variation_a     0/5      0/15
variation_b    15/15    14/14
```

**Review by kellyroach-optimizely — APPROVED** [review]
APPROVED

**Pull request merged**
