### PR TITLE
feat(api): Accepting all types for attributes values

### PR DESCRIPTION
**Pull request by AbdurRafay**
### Summary
To support all types of attribute values I changed all relevant function signatures from NSDictionary<NSString *, NSString *> to NSDictionary<NSString *, NSObject *> so that it can accepts an Object variable rather than just a String for functions that accept and uses attributes.

### Testing
All types of attributes are added in Optimizely and EventBuilder test cases and they are passing.

### CODE REVIEW

**Comment by msohailhussain** [comment]
build

**Comment by msohailhussain** [comment]
build

**Review by thomaszurkan-optimizely — CHANGES_REQUESTED** [review]
You forgot some methods such as Optimizely.m line 885.  Also, we need to update the notification listeners and the decision service tests.

**Review by thomaszurkan-optimizely — APPROVED** [review]
LGTM

**Comment by msohailhussain** [comment]
@mikeng13 Can you merge this branch?

**Pull request merged**
