### PR TITLE
write failing test

### PR DESCRIPTION
**Pull request by wangjoshuah**

### CODE REVIEW

**Comment by kellyroach-optimizely** [comment]
TEST FAILED
``- (void)testSingleQuoteStringSaveAndRemove``
did fail.  Can we have a JIRA ticket number or more explanation?
Is this a new regression test illustrating a bug which is about to be fixed?

**Review by kellyroach-optimizely — CHANGES_REQUESTED** [review]
New test failed.  Requesting more info.

**Review by thomaszurkan-optimizely — APPROVED** [review]
LGTM

**Comment by kellyroach-optimizely** [comment]
REPORTED AS OASIS-2636

I recommend a solution be checked in with the failing test.  I recommend against checking
in a failing test without a solution since many issues have different priorities for us and
failing tests are a distraction and noticeable on Travis if they stay unfixed for a prolonged
period of time.  Currently, all our unit tests do pass and it would be changing procedure to
check in unit tests which don't pass.

**Comment by aliabbasrizvi** [comment]
Closing as this is being addressed in https://github.com/optimizely/objective-c-sdk/pull/236

**Pull request closed without merging**
